{% set name = "pytest-flakes" %}
{% set version = "4.0.5" %}
{% set sha256 = "953134e97215ae31f6879fbd7368c18d43f709dc2fab5b7777db2bb2bac3a924" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - python >=3.5
    - pytest-cache
    - pytest >=2.4.0
    - pyflakes

test:
  imports:
    - pytest_flakes


about:
  home: https://github.com/fschulze/pytest-flakes
  license: MIT
  license_file: LICENSE
  summary: pytest plugin to check source code with pyflakes

extra:
  recipe-maintainers:
    - bjodah
    - asmeurer
